---
title: "Yuhan Wu's Personal Website"
description: |
  Welcome to the website. I hope you enjoy it!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

## Introduction

Hello, my name is Yuhan Wu. I am currently a student at Newton North High School. When I was young, I have always wondered what are the real application of all the math and science knowledge that I've learned. I discovered the answer to this question after my first math modeling competition; I came to the realization and the fascination of the power of data analytics and mathematical modeling. It is the pleasure of creation and seeing its application that keeps motivate me and pushes me further in the journey of math and data.

I am an amateur badminton player and a pianist ([Performance at Asian Night](https://www.youtube.com/watch?v=zAMLrC4QClM&t=1980s)). On to food, I am a crazy burritos lover since my first exposure to it during a math modeling competition. 

This website will keep track of my several main projects throughout high school, as well as progress and knowledge development as I dive deeper into the fields of applied mathematics and data science.

Hope you can find this website interesting and can learn a little more about me!

Welcome again! ฅ՞•ﻌ•՞ฅ

_Yuhan_


## Modeling Exploration

This section record my explorations and the learning of different algorithms, theories and methods of data analysis. 

These topics includes:

- [Linear Programming](01-linear-programming.html)
- [Graph Theory](02-graph-theory.html)
- [Interpolation and Fitting](03-interpolation-fitting.html)
- [Analytic Hierarchy Process (AHP)](04-analytic-hierarchy-process.html)
- [Integer Programming](05-integer-programming.html)
- [Dynamic Programming](06-dynamic-programming.html)
- [Differential Equation Modeling](07-differential-equation.html)
- [Game Theory](08-game-theory.html)
- [Queueing Theory](09-queueing-theory.html)
- [Inventory Theory](10-inventory-theory.html)

## Projects Overview





